# Generated by Django 4.0.3 on 2022-04-28 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('7a976ac8-9e97-4357-97c7-ec8390752b3d'), editable=False, max_length=200),
        ),
    ]
