# Generated by Django 4.0.4 on 2022-05-01 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f3febd53-31d3-403a-84e0-882b825458ac'), editable=False, max_length=200),
        ),
    ]
