# Generated by Django 4.0.3 on 2022-05-17 06:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
        ('customers', '0002_alter_customer_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_receiver', models.CharField(max_length=50)),
                ('phone_receiver', models.CharField(max_length=15)),
                ('address_receiver', models.CharField(max_length=200)),
                ('messages', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c968d966-90b7-42c5-99fc-e40ee9166c10'), editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ManyToManyField(to='customers.order')),
                ('product_id', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
    ]
