# Generated by Django 4.0.3 on 2022-05-17 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
        ('customers', '0003_order_alter_customer_token_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('90db0e67-6e22-463d-ab7b-a8e3256f83fa'), editable=False, max_length=200),
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order_product',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.order'),
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_product',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
