# Generated by Django 4.0.3 on 2022-04-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0003_alter_manufacturer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(upload_to='images/manufacturers'),
        ),
    ]
